on:
  workflow_dispatch:

name: Build Installer Formats

jobs:
  build:
    ## We want to define a strategy for our job
    strategy:
      ## this will contain a matrix of all of the combinations
      ## we wish to test again:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        arch: ["amd64", "arm64"]

    ## Defines the platform for each test run
    runs-on: ${{ matrix.platform }}

    ## the steps that will be run through for each version and platform
    ## combination
    steps:
      ## sets up go based on the version
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      ## checks out our code locally so we can work with the files
      - name: Checkout code
        uses: actions/checkout@v2

      - if: matrix.platform == 'windows-latest'
        run: |-
          SET GOARCH=${{ matrix.arch }}
          mkdir -p ./out
          cd installer
          go build -o ../out/akcmd_installer.exe
      - if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: akcmd_installer-${{ matrix.platform }}_${{ matrix.arch }}
          path: ./out/akcmd_installer.exe

      - if: matrix.platform != 'windows-latest'
        run: |-
          export GOARCH=${{ matrix.arch }}
          mkdir -p ./out 
          cd installer
          go build -o ../out/akcmd_installer
      - if: matrix.platform != 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: akcmd_installer-${{ matrix.platform }}_${{ matrix.arch }}
          path: ./out/akcmd_installer
